[profile.default]
solc = '0.8.19'
src = 'src'
test = 'test'
script = 'script'
out = 'out'
evm_version = 'paris'
libs = ['lib']
remappings = [
] 
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
amoy = "${RPC_AMOY}"
[etherscan]
# CATAPULTA

# See more config options https://github.com/gakonst/foundry/tree/master/config
